### ISSUE TITLE
hxparse git dependency conflict

### ISSUE THREAD

**Issue by ddamerell53** [dpeek/dox#100]
When following the instructions to install dox both hxparse and hxtemplo are installed from git.

However it appears that hxparse has introduced an incompatibility with the current version of hxtemplo.

For me installing hxparse straight out of haxelib fixed the issue (first remove hxparse and then reinstall).

Could you update the instructions?

**Comment by Simn** [comment]
What incompatibility are you talking about? Our CI rebuilds Dox from git which works just fine.

Either way, if there is an issue it's not a Dox issue. Git versions have git dependencies (including Haxe itself), haxelib versions have haxelib dependencies.

**Comment by ddamerell53** [comment]
Does your CI follow the set-up instructions on the web-site?

i.e. try installing the released Haxe 3.1.3 from the Haxe web-site and then follow the instructions on your web-site to install dox.

Apologies if this works for you but it didn't for me.

**Comment by Simn** [comment]
Git hxparse requires git Haxe.
