### ISSUE TITLE
Generate package-level comments.

### ISSUE THREAD

**Issue by vbence** [dpeek/dox#104]
Feature request: The ability to write some [comments over a package listing][1] would be really useful.

[1]:http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#packagecomment

**Comment by Simn** [comment]
Can't really do that unless the Haxe XML export is changed to actually contain that information. This would require changes to the Haxe parser and internal data structure, so I don't see it happen anytime soon.

**Comment by vbence** [comment]
@Simn That was my first idea too, but at the second look: Java can use source files called `package-info.java`. These comments CAN be put in the XML file, if there was a convention, Dox could associate them with the package.
