### ISSUE TITLE
Platform select on haxe-api theme is gone

### ISSUE THREAD

**Issue by Simn** [dpeek/dox#105]
I've just up uploaded the Haxe API docs with the new theme to http://api.haxe.org/v/dev/. Only then I noticed that the platform selection is gone. We'll need that back before we can use it as a default.

@markknol: Could you check this?

**Comment by markknol** [comment]
That is a good point, ill look into that soon. I dont know how that dropdown works yet.

Btw docs look nice! I only wonder why the version is "development", can that be a bit more specific?

**Comment by Simn** [comment]
I don't really know how it works either, but I know that it did work. :D

**Comment by Simn** [comment]
There are some other issues. It looks like this theme forked off an older version of the default theme. For example methods do not have their `inline` or `dynamic` modifiers which the default theme handles in `printFieldSignature`.

**Comment by Simn** [comment]
Also there's a terminology issue with "properties". In Haxe a property is a variable with access modifiers such as `var x(default, null)`. The theme uses "properties" as summary for Haxe properties and Haxe variables. Furthermore it doesn't display the access modifiers of actual properties and only recognizes "read-only".

**Comment by markknol** [comment]
Ill check the modifiers too. 

What is a better term for "properties"? "Fields"?

Do you know how to fill the list with all platforms? If i run dox on a project it only has only one platform in the list.
