### ISSUE TITLE
nested packages bug(?)

### ISSUE THREAD

**Issue by yupswing** [dpeek/dox#116]
Hello dpeek,
I have a package called com.mydomain.mylibrary

when I've got all the xml (in the bin/xml folder) written and I launch
```haxelib run dox -o docs -i bin/xml -in com```
I get just my package

if I run the command
```haxelib run dox -o docs -i bin/xml -in com.mydomain```
to really filter just my packages (there could be something else in the top COM)
I get nothing

I've tried with something common like openfl filtering ```-in openfl``` (it works) and after ```-in openfl.display``` (it doesn't work)

Am I doing something wrong (maybe I didn't understand completely the -in arg) or is there a bug?

Thanks

**Comment by Simn** [comment]
Is this git dox or haxelib dox?

**Comment by yupswing** [comment]
I was using haxelib dox
I've just moved to the git dox to be sure it was a current problem.
Same behaviour.

**Comment by yupswing** [comment]
````sh
% haxelib list dox
dox: git [dev:/usr/lib/haxe/lib/dox/git]

% haxelib run dox -o docs -i bin/xml -in com
Parsing bin/xml/neko.xml
Processing types
..
Generating navigation
Generating to docs
.
Generated 1 types in 4 packages
Copying resources from /usr/lib/haxe/lib/dox/git/themes/default/resources
Done (1.539s)

% haxelib run dox -o docs -i bin/xml -in com.mydomain
Processing types

Generating navigation
Generating to docs

Generated 0 types in 1 packages
Copying resources from /usr/lib/haxe/lib/dox/git/themes/default/resources
Done (0.027s)
````

**Comment by Simn** [comment]
Could you try again now? It looks like the problem was that the parent packages got filtered out.

**Comment by yupswing** [comment]
Great! It works perfectly.
Thank you very much for dox and especially for this fix ;)

**Comment by Simn** [comment]
\o/
