### ISSUE TITLE
Move dox to Haxefoundation Github?

### ISSUE THREAD

**Issue by markknol** [dpeek/dox#119]
Since dox is now thé Haxe API generation tool, wouldn't it be an idea to connect this repository to the https://github.com/HaxeFoundation page?

**Comment by Simn** [comment]
I kind of enjoy having David's github here so I don't have to feel responsible for _everything_. :P

**Comment by markknol** [comment]
Haha ok, I mostly suggested it so it does not feel as single user project (while thats already not true) but part of the toolkit.

**Comment by dpeek** [comment]
Although my responsibility has been severely lacking of late! But yes, no need to put all your libs in one basket :P

I'm just back from a month of holiday, dox is back on my radar.
