### ISSUE TITLE
Generated xml file causes issues for dox under OpenFL 3.0.0-beta.3

### ISSUE THREAD

**Issue by aurodev** [dpeek/dox#123]
Generated xml file causes issues for dox (and chxdoc) under OpenFL 3.0.0-beta.3
Both work properly under OpenFL 2.2.8

Dox

Parsing myGeneratedDocs.xml
Dox.hx:124: Error while parsing myGeneratedDocs.xml
Called from ? line 1
Called from dox/Dox.hx line 138
Called from dox/Dox.hx line 125
Uncaught exception - xml.c(80) : Xml parse error : Expected > at line 36289 : ...\&*()[]{}<>|:;_-+=?,. '">
<c...

xml Generated with:
haxeflag name="-xml" value="myGeneratedDocs.xml"

Environment:

Win8.1

actuate: [1.8.3]
box2d: [1.2.3]
chxdoc: [1.3.0]
dox: [1.0.0]
flixel-addons: [1.1.0]
flixel-demos: [1.1.1]
flixel-templates: [1.0.2]
flixel-tools: [1.0.5]
flixel-ui: [1.0.2]
flixel: 3.3.6 [3.3.8]
hxcpp: [3.2.37]
hxcs: [3.2.0]
hxjava: [3.2.0]
iap: [1.0.6]
layout: [1.2.0]
lime-samples: [2.2.0]
lime-tools: [1.5.7]
lime: 2.1.2 2.2.1 [2.3.0]
openfl-bitfive: 2.1.6 [3.0.0]
openfl-samples: [2.2.2]
openfl: 2.2.8 [3.0.0-beta.3]
swf: [1.8.2]

**Comment by Simn** [comment]
Not a Dox issue. Might be a Haxe issue so feel free to report there. You might want to check what exactly is causing problems in the XML file yourself though.

**Comment by aurodev** [comment]
Understood. Thought this might be relevant though.
Seems to be an issue only with OpenFL 3.0.0-beta.3.   
Setting to OpenFL 2.2.8 to build/generate xml works fine.

Thought you might want to know going forward since OpenFL is changing a bit.

**Comment by scriptorum** [comment]
@aurodev I've seen this issue too. There are improperly escaped characters in the -xml output. `\"` instead of `&quot;`. I got dox to run (on OS X) by doing a replacement on the output file:
```bash
sed -i "" -e 's/\\\"/\&quot;/g' -e 's/\\\&/\&amp;/g' dox.xml
```
Have you filed an issue with lime?
