### ISSUE TITLE
No bullets show unless list preceded by blank line

### ISSUE THREAD

**Issue by scriptorum** [dpeek/dox#124]
I believe this markup should show a bullet:
```haxe
/**
 * Some comment
 * - Some bullet
 */
```
But instead it renders like this: `Some comment - Some bullet`.

Adding a blank line in between the comment and the bullet list restores the bullet.

*GitHub markup dramatization:*

Some comment
 - Some bullet

**Comment by dpeek** [comment]
Moved here https://github.com/dpeek/haxe-markdown/issues/19
