### ISSUE TITLE
How do I compile this project?

### ISSUE THREAD

**Issue by maxless** [dpeek/dox#125]
I'm on Haxe 3.1.3 and "haxe run.hxml" produces this error message:
```
/usr/lib/haxe/lib/hxparse/git/src/byte/ByteData.hx:3: lines 3-68 : Class not found : haxe.io.UInt8Array
src/dox/Config.hx:4: lines 4-75 : Defined in this class
/usr/lib/haxe/lib/hxparse/git/src/byte/ByteData.hx:6: characters 8-48 : Class not found : haxe.io.UInt8Array
```
I've tried to get haxe.io.UInt8Array from Haxe git but it just produces more errors.

**Comment by Simn** [comment]
If you use git versions you're gonna need Haxe 3.2/development. Haxelib versions should work with 3.1.3.
