### ISSUE TITLE
Hyperlinks rendered incorrect 

### ISSUE THREAD

**Issue by markknol** [dpeek/dox#127]
Http://api.haxe.org/haxe/Template.html
See class description, seems like some links are not rendered nicely. Also link to 404 because of it.

**Comment by markknol** [comment]
What is the correct way to declare a hyperlink to a external page? I notice that  `@see http://www.bla` doesn't create hyperlinks too. And  `<a href=¨¨>` seems to create incorrect rendered links.

**Comment by dpeek** [comment]
So, the markdown library detects links like `http://google.com`, there is no need to add the `<a>` tag. If you want a link with a name you use `[name](http://link.com)`.

At the moment we don't support `@see` but I'll add that. I think my reasoning was that it was easy enough to link to stuff from the doc itself (ie. see http://link.com)

**Comment by markknol** [comment]
http://api.haxe.org/php/Lib.html#mail << there are urls in this description, but they don't get parsed as hyperlinks.

**Comment by dpeek** [comment]
Obviously this one isn't closed quite yet then :)

**Comment by dpeek** [comment]
Moved here https://github.com/dpeek/haxe-markdown/issues/20
