### ISSUE TITLE
Code blocks not rendered correct

### ISSUE THREAD

**Issue by markknol** [dpeek/dox#128]
See:
http://api.haxe.org/cs/Flags.html

The source looks like this:
https://github.com/HaxeFoundation/haxe/blob/development/std/cs/Flags.hx#L7-L11

**Comment by dpeek** [comment]
Ok, not entirely sure what is going on here, but the additional indentation on the code block is not required. So, it should look like this:

```
/**
	Use this type to have access to the bitwise operators of C# enums that have a `cs.system.FlagsAttribute` attribute.

	```haxe
	import cs.system.reflection.BindingFlags;

	var binding = new Flags(BindingFlags.Public) | BindingFlags.Static | BindingFlags.NonPublic;
	```
**/
```

I suspect this is another whitespace trimming bug.

Also, shouldn't this be:

```haxe
new Flags(BindingFlags.Public | BindingFlags.Static | BindingFlags.NonPublic);
```

And also the haxe-api template helpfully adds a little "Example" tag thing top left when it is Haxe source, which means you don't really have to write "Usage example".

**Comment by dpeek** [comment]
Actually, it shouldn't break like this...
