### ISSUE TITLE
missing "?" for optional arguments

### ISSUE THREAD

**Issue by ScrambledRK** [dpeek/dox#131]
optional method/constructor arguments prefixed with a question mark symbol are shown as they were required (no question mark, no "optional" description for @param)

expected result:
* optional arguments keep their "?" prefix in the generated html documentation
* nice to have: @param automatically adds an "optional" qualifier 

the question mark seems to be in the generated *.xml used to create the html files, so I suppose its a html generation issue/feature request.

**Comment by Gama11** [comment]
Related: https://github.com/dpeek/dox/issues/68

**Comment by Simn** [comment]
Didn't we fix that?

**Comment by ScrambledRK** [comment]
the question mark is still missing - usually it shows the argument type as: `myArgument:Null<MyArgumentType>` which indicates an optional parameter, but it only seems to work if there is no default value specified. for example: `new( ?pivot:IVector3 = null )` still generates as if the argument is required.
