### ISSUE TITLE
@:enum abstract string values

### ISSUE THREAD

**Issue by markknol** [dpeek/dox#132]
Just stumbled on this one:
http://api.haxe.org/js/html/XMLHttpRequestResponseType.html
source: https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/XMLHttpRequestResponseType.hx

Would it be possible to have the actual values there instead of `???`

**Comment by Simn** [comment]
This should have been fixed by @Gama11's expression printer update, I just have to regenerate the API documentation and/or wait for @jasononeil to automate it.

**Comment by markknol** [comment]
Ah nice! well, just regenerate it (along with the manual updates) :smile:

**Comment by markknol** [comment]
Fixed in dev http://api.haxe.org/v/dev/js/html/XMLHttpRequestResponseType.html

**Comment by aW4KeNiNG** [comment]
Hi.

I have the same problem with the current git master version.

My code is:

```
@:enum
abstract OutputFormat(String) from String to String
{
    var SOURCE                  = "source";
    var SPHERICAL               = "spherical";
}
```

Do you have the same problem?

Cheers.

**Comment by Gama11** [comment]
You need to generate the xml using a dev build of Haxe.

**Comment by aW4KeNiNG** [comment]
Ah!

Thanks @Gama11 :)
