### ISSUE TITLE
broken html because of < > in documentation

### ISSUE THREAD

**Issue by markknol** [dpeek/dox#133]
If the documentation contains < or > it should be converted to html entities. Now the html is broken (its missing lots of methods, and footer is gone.

.. or should this be fixed in the documentation itself?

**source**
https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/HTMLDocument.hx
**api**
http://api.haxe.org/js/html/HTMLDocument.html

**Comment by dpeek** [comment]
Documentation is in markdown, and in markdown HTML tags get left alone. I'm guessing backticks might work, like `<br>`, if not they'll need to be escaped.
