### ISSUE TITLE
Awkward line breaks in function argument lists

### ISSUE THREAD

**Issue by Gama11** [dpeek/dox#136]
![](http://i.imgur.com/uY6ChsZ.png)

`?NotifyCallback` should be considered as a single word.

**Comment by Gama11** [comment]
Similary, it's weird to have a line break here for the `= expr` part:

![](http://i.imgur.com/Syf4dZn.png)

**Comment by Simn** [comment]
What can we actually do about that?

**Comment by dpeek** [comment]
`&nbsp;` to the rescue? In the second case at least. Not sure how we do it for ?name, maybe put in a "white-space:nowrap" span?

**Comment by dpeek** [comment]
`&nbsp;` – not just for fixing layout issues in IE5
