### ISSUE TITLE
Expressions of abstract enum values have a `cast`

### ISSUE THREAD

**Issue by Gama11** [dpeek/dox#146]
See [here](http://api.haxeflixel.com/flixel/text/FlxTextAlign.html) for example:

![](http://i.imgur.com/jaTgwtu.png)

The source code doesn't have that `cast`, so it shouldn't appear in the docs.

**Comment by Simn** [comment]
We could address this in Haxe but I'm not sure if we should. It's probably an easy fix to make in Dox.

Waiting for a pull request!
