### ISSUE TITLE
"Type anywhere to search"

### ISSUE THREAD

**Issue by Gama11** [dpeek/dox#149]
The [Luxe API docs](http://luxeengine.com/docs/api/index.html) have this feature, and it seems quite convenient. Probably don't need a whole new UI for this, could just give the existing search field focus on keyboard events.

Might need to indicate somehow that you can use it this way, maybe change the default text in the search field from `Search` to `Type anywhere to search...`?

**Comment by Simn** [comment]
Can we just on-load focus to the text field and call it a day? That's what google.com does as well.

**Comment by Gama11** [comment]
Yeah, not a bad idea. There aren't a lot of scenarios where you'd lose focus either, except maybe swtiching the platform in the dropdown..
