### ISSUE TITLE
Javadoc handling fails if comment indent is mix of tabs and spaces

### ISSUE THREAD

**Issue by Gama11** [dpeek/dox#163]
```haxe
	/**
 	 * HaxeFlixel's graphic caching system keeps track of loaded image data. 
 	 * When you load an identical copy of a previously used image, by default
	 * 
	 * @param	Graphic		The image you want to use.
	 */
	public function loadGraphic(Graphic:String) {}
```

results in:

![](http://i.imgur.com/qknYbOM.png)

There's a single space at the start of the 2nd and 3rd line, spaces for the rest, which causes this:

![](http://i.imgur.com/eeSbPXY.png)

**Comment by Simn** [comment]
That falls under "fix your indentation", see https://github.com/dpeek/dox/issues/83#issuecomment-104291615

**Comment by Gama11** [comment]
Hm... seems like it should be a bit more robust, but fair enough.

**Comment by Simn** [comment]
Sure that would be nice, but Javadoc is surprisingly terrible to parse.
