### ISSUE TITLE
Hexadecimal value

### ISSUE THREAD

**Issue by ibilon** [dpeek/dox#82]
A small cosmetic issue,
when using a hexadecimal value in the code, for stuff like color: `color:Int = 0xFFFFFF`
end up looking like this `?color:Int = 16777215` which is kind of weird.

No idea how to fix that though,
maybe something like a parameter to `@param` like `@param(hex)`?

**Comment by Simn** [comment]
I just checked with a small example and this is working now. Please let me know soon if you come across any issues.
