### ISSUE TITLE
Regression: @param does not work

### ISSUE THREAD

**Issue by Atry** [dpeek/dox#83]
``` haxe
/**
  @param x some documentation for parameters.
**/
public function foo(x:Int):Void
{
}
```

The `@param` is not recognized after https://github.com/dpeek/dox/commit/a467b60b985fdbce1ab9dfff079181bf0d29b62a

**Comment by Simn** [comment]
I'm not sure if we should merge this or not. The metadata parsing problem is a bit scary...

**Comment by maxless** [comment]
So... half a year has passed since the issue was opened. Is there any way to make space-indented tags work?

**Comment by dpeek** [comment]
Ok, I'm going to call this closed by https://github.com/dpeek/dox/commit/35f45b38a02b94d4947c7645e6ba6f39eab3447d

We detect indentation as: the indentation of the line (other than the first) that matches the condition (some spaces/tabs)(optional asterix AND space)(non-space char other than asterix)

There is a test for this `@param` issue in particular here https://github.com/dpeek/dox/blob/master/test/TestClass.hx#L108
