### ISSUE TITLE
Allow specifying multiple toplevel packages

### ISSUE THREAD

**Issue by Gama11** [dpeek/dox#90]
#46 is working nicely, but it limits API docs to only one library / package - for example for flixel, we would like to provide the API for flixel / nape / OpenFL all conveniently in one place.

The `--toplevel-package` option could be turned into `--toplevel-packages`:

`--toplevel-packages flixel, flixel.addons, flixel.addons.ui, nape, flash`

Presentation-wise this could be done via an additional dropdown-menu next to the one for targets:

![](http://i.imgur.com/2hce7Ya.png)

**Comment by Simn** [comment]
That might require quite a bit of work. I'm not strictly against it but I don't think anyone is going to look into it anytime soon.

**Comment by Gama11** [comment]
With the search improvements, I'm not really too interested in this anymore.
